### ISSUE TITLE
Issue cleanup

### ISSUE THREAD

**Issue by jeromekelleher** [mcveanlab/treeseq-inference#53]
Some of the issues here are quite general and not really on the subject of the repo (that is, providing a reproducible and long-term stable home for the code in the paper).

Would you mind going through the issues and closing any that are off-topic please @hyanwong? If you want to keep them alive somewhere then you can clone this repo to your own account.

**Comment by hyanwong** [comment]
Closed or moved most of these. A few active ones left.
