### ISSUE TITLE
Add code to produce figure S1.

### ISSUE THREAD

**Issue by jeromekelleher** [mcveanlab/treeseq-inference#57]
Figure S1 needs simulation code in this repo. Create a file ``src/misc-simulations.py`` following the model of ``src/storing_everyone.py`` which will do this. The script should write a CSV file called ``data/allele_age_frequency.csv``.  Commit the CSV file.

Update ``src/plot.py`` to produce this figure (allele_age_frequency) following example of StoringEveryone.

Open a PR with the results when it's ready.

**Comment by awohns** [comment]
I think this is all set now. If so, should we close this issue?

**Comment by hyanwong** [comment]
Yes.
