### ISSUE TITLE
Change selective sweep code to use SLiM

### ISSUE THREAD

**Issue by hyanwong** [mcveanlab/treeseq-inference#59]
I think for main submission we should change the code to simulate a sweep using SLiM. I'm happy to make this change. The results should be identical, I would hope.

**Comment by hyanwong** [comment]
Now on branch "slim"

**Comment by jeromekelleher** [comment]
Presumably we could make the examples a little bit bigger as well, since SLiM should be a lot faster?

**Comment by hyanwong** [comment]
Sure, although it's mainly the argweaver inference that slows it down, not the forward simulating.

**Comment by hyanwong** [comment]
This is merged
