### ISSUE TITLE
Making empirical error faster

### ISSUE THREAD

**Issue by awohns** [mcveanlab/treeseq-inference#61]
Yan and I rewrote make_errors_genotype_model in evaluation.py. Update is on branch "improved_error_function"
Needs to be tested more and merged into master

**Comment by hyanwong** [comment]
@awohns: there doesn't seem to be anything pushed to that branch yet. Have you synced your local repo?

**Comment by hyanwong** [comment]
@awohns - there's an error on line 118 - you should be reshaping the new (copied) matrix `w`, not the original one `g`.

**Comment by awohns** [comment]
fixed

**Comment by jeromekelleher** [comment]
Is this closable?

**Comment by hyanwong** [comment]
I'm testing it on the selective sweep example, and it seems fine, although I should probably double check with e.g. the generic neutral examples. We can't test whether it gives exactly the same results, as one of the efficiencies is calling the RNG routines less frequently (was overusing them before).

**Comment by jeromekelleher** [comment]
Should be able to compare the distributions before and after easily enough? If they're the same on on some simple tree sequence, then it should be fine.

**Comment by hyanwong** [comment]
Yep - doing.

**Comment by hyanwong** [comment]
I've checked on this. It looks fine to me. We can probably merge the improved_error_function branch.

**Comment by hyanwong** [comment]
Merged into the SLiM branch which was in turn merged into master
