### ISSUE TITLE
Availability of UKB tree sequences and GNN

### ISSUE THREAD

**Issue by Chris1221** [mcveanlab/treeseq-inference#71]
Hi guys,

I was reading the notebook for analyzing the UKB data [here](https://github.com/mcveanlab/treeseq-inference/blob/master/human-data/UKB_plot.ipynb). I was wondering if the output data at various points of the notebook was deposited anywhere? Things like `gnn_nuts2.csv`, `ukb_reverse_geocoded_nuts2.csv`, the tree sequence referred to in `ts_path`, etc. More generally, is the pre-computed ts for the UKB available, either by request or publicly?  

Thank you

**Comment by hyanwong** [comment]
We aren't allowed to release any intermediate data products publicly (or indeed privately!) that could be seen as releasing any of the dataset.

We could, I suppose, released some of the summary GNN values (e.g. the values actually plotted in some of the released plots). As far as I know, we haven't done so yet, however. I guess we might want to check with UKBB that this would be OK.

**Comment by hyanwong** [comment]
Some of the more detailed GNN analysis run rather close to the line of being able to deanonymise genomes in UKBB, so we need to be super careful, even with the data summaries.

**Comment by Chris1221** [comment]
That's fair, thanks Yan. If you do decide to release any summary level GNNs, I think it would certainly be useful to the community but of course I appreciate the importance of not being able to deanonymise individuals.
