### ISSUE TITLE
R-Python linkage is complex

### ISSUE THREAD

**Issue by jeromekelleher** [mcveanlab/treeseq-inference#9]
I'm having trouble getting the R-Python linkage working. A few points:

1. Do we really need a R package for ARGMetrics? Would it be possible to just use a script that can be imported locally, rather than needing to be installed into the local R installation?

2. I realise there is a lot of work gone in here already, but is there any way we could replicate this functionality in Python? [dendropy](https://pythonhosted.org/DendroPy/library/treecompare.html) has an R-F metric implementation. It might be simpler in the long run...

3. If we choose to keep the rpy2 linkage, can we isolate this into a single module, so it's clear where we're actually using it?

**Comment by hyanwong** [comment]
I think the current install instructions are as good as we are going to get
